### ISSUE TITLE
sass import, 문법문제 

### ISSUE THREAD

**Issue by SoYoung210** [YAPP13-4/semi-basement#21]
1. Artworkplay 구조
song body info 안쪽에 title, singer div 위치. 
![image](https://user-images.githubusercontent.com/18658235/45342572-57c72600-b5d9-11e8-850f-027ba3f14543.png)

```jsx
class ArtworkPlay extends Component {
    
    render() {
        const artworkUrl = this.props.artwork;
        return(
            <div className={cx(`${moduleName}`)}>
                <div className={cx(`${moduleName}-row`)}>
                    <div className={cx(`${moduleName}-row__cell`)}>
                        <div className={cx(`${moduleName}-song-body-card`)}>

                            <div 
                                className={cx(`${moduleName}-song-body-card-artwork`)}
                               style= {{backgroundImage: `url(${getImageUrl(artworkUrl, IMAGE_SIZES.XLARGE)})`}}
                            >
                           </div>
                           <div className={cx(`${moduleName}-song-body-card-info`)}>
                                <div className ={cx(`${moduleName}-song-body-card-title`)}>
                                    {this.props.title}
                                </div>
                                <div className ={cx(`${moduleName}-song-body-card-singer`)}>
                                    {this.props.singerName}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        )
    }
}
```

Artworkplay.scss

```scss
.ArtworkPlay {
    &-row {
        padding-top: 27px;
    }
    &-song-body-card {
        width: 188px;
        height: 243px;
        border-radius: 3px;
    }
    &-song-body-card:hover {
        background-color: #393939;
        .song-body-card-singer {  //here!!!
            color: white;
        }
    } 
}
```

song body card가 호버되었을 때 저렇게 singer div의 스타일로 `color white` 주고싶은데,, 

classname.bind 방식으로 쓰는 css가 처음이라 어떻게 할지 잘 모르겠네요 .

2. 
![image](https://user-images.githubusercontent.com/18658235/45342600-67466f00-b5d9-11e8-86a9-7fadd3dd35cc.png)

그리고 font 파일도 공용적으로 위치시킨다음 sass파일에서 import시켜보고 싶은데,,,,,,,,,,,, 
@Import "../../font" 뭐 이런식으로 경로맞춰서 써줘도 접근할 수 없다고 뜨더라구요 ㅠ 

@livelikeabel  도움부탁드립니다 !_!
