### ISSUE TITLE
나중에 고쳐야 할 사항 

### ISSUE THREAD

**Issue by SoYoung210** [YAPP13-4/semi-basement#33]
**noti**

![image](https://user-images.githubusercontent.com/18658235/45916425-fccae400-bea0-11e8-9443-9026106e0376.png)
우선 여기서 `+`버튼은 원래 DB와 연동되는 `MyPlayList` 이지만, 현재는 `History` 탭에 추가하는 것으로 대체한다. 

나중에 Server 가 셋팅 되면, 기능과 Action을 정리해야 한다.

**Comment by SoYoung210** [comment]
![image](https://user-images.githubusercontent.com/18658235/45927420-b55e5980-bf6d-11e8-9356-bc58def29974.png)

```scss
.HistoryTab {
  overflow-x: scroll;
  &__Wrapper {
    display: flex;
    //딱 맞게 어떻게 하지... 아직 모르겠다. ㅠ
    width: 5000px;
  } 
}
```

`HistoryComponent` 개수가  몇 개인지에 따라 `width` 를 계산해주어야 하는데.. 도저히 어떻게 할지 실마리가 없어서 일단 그냥 `5000` 으로 정해두고 (무조건 스크롤 되는중 ..) 나중에 css 를 고쳐보기로 하자.
