### ISSUE TITLE
새로운 music player와 history Tab 연결 

### ISSUE THREAD

**Issue by SoYoung210** [YAPP13-4/semi-basement#42]
(구) 뮤직플레이어 였던 `BottomPlayer.js ` 이다. 

새로운 music Player 에도 `toggleHistoryTab` 을 추가하자. 
 
```jsx
import React, { Component } from 'react'
import ReactPlayer from 'react-player'
import classnames from 'classnames/bind'
import { connect } from 'react-redux' 
import { bindActionCreators } from 'redux'
import { toggleHistory } from '../../../redux/meta/actions'
import { SONG_URL } from '../../constants/ApiConstants'
import HistoryTab from '../HistoryTab/HistoryTab'
import css from './index.scss'
const cx = classnames.bind(css)
const moduleName = 'BottomPlayer'
  class BottomPlayer extends Component {
    
    render() {
        return (
          <div className={cx(`${moduleName}`)}>
            <ReactPlayer className={cx(`${moduleName}`+(this.props.toggleHistoryTab ? '-player' : '-hidden')  ) } url={this.props.song} controls={true}/>
            
            <button onClick={this.props.toggleHistory}> history  </button>
            <div className={cx(`${moduleName}-historyTab`)}><HistoryTab /></div>
          </div>
        )
      }
}
function mapDispatchToProps(dispatch) {
  return bindActionCreators({toggleHistory} , dispatch)
}


function mapStateToProps(state) {
  const songurl = (SONG_URL.replace(':id', state.music.song));
  return { 
        song : songurl,
        toggleHistoryTab : state.meta.toggleHistory  
      }
}


export default connect(mapStateToProps,mapDispatchToProps)(BottomPlayer)

```

//css
```scss
.BottomPlayer { 
    &>div {
        width: 1440px !important;
        height: 75px !important;
        position: fixed;
    }
    &>div.BottomPlayer-hidden {
        bottom: 0;
    }
    &>div.BottomPlayer-player {
        bottom: 75px;
    }
    &-historyTab {
        bottom: 0;
    }
}
```
